// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package handler

import (
	"net/http"

	"github.com/heimdall-api/public-api/public/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 测试接口
				Method:  http.MethodGet,
				Path:    "/test/:name",
				Handler: PublicHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/public"),
	)
}
