// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/heimdall-api/public-api/public/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/posts",
				Handler: GetPublicPostListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/posts/:slug",
				Handler: GetPublicPostDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/pages/:slug",
				Handler: GetPublicPageDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tags",
				Handler: GetPublicTagListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tags/:slug",
				Handler: GetPublicTagDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/posts/:postSlug/comments",
				Handler: GetPublicCommentListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/posts/:postSlug/comments",
				Handler: CreateCommentHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/comments/:commentId/replies",
				Handler: GetCommentRepliesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/comments/:commentId/replies",
				Handler: CreateReplyHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/public"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/site/info",
				Handler: SiteInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/site/navigation",
				Handler: NavigationMenuHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/site/settings",
				Handler: PublicSettingsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/posts/popular",
				Handler: PopularPostsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/posts/recent",
				Handler: RecentPostsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/posts/trending",
				Handler: TrendingPostsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/posts/:slug/related",
				Handler: RelatedPostsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/public"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/robotstxt",
				Handler: RobotsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/sitemapxml",
				Handler: SitemapHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/rssxml",
				Handler: RSSFeedHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/feedjson",
				Handler: JSONFeedHandler(serverCtx),
			},
		},
		rest.WithPrefix("/"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/test/:name",
				Handler: PublicHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/public"),
	)
}
