// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type BaseResponse struct {
	Code      int    `json:"code"`
	Message   string `json:"message"`
	Timestamp string `json:"timestamp"`
}

type TestRequest struct {
	Name string `path:"name,options=you|me"`
}

type TestResponse struct {
	Message string `json:"message"`
}
