// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/heimdall-api/admin-api/admin/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/auth/login",
				Handler: LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/admin"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/auth/profile",
				Handler: ProfileHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auth/logout",
				Handler: LogoutHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auth/refresh",
				Handler: RefreshTokenHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auth/change-password",
				Handler: ChangePasswordHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/users",
				Handler: GetUserListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/users",
				Handler: CreateUserHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/users/:id",
				Handler: GetUserDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/users/:id",
				Handler: UpdateUserHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/users/:id",
				Handler: DeleteUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/users/:id/status",
				Handler: UpdateUserStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/users/:id/role",
				Handler: UpdateUserRoleHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/users/:id/reset-password",
				Handler: ResetUserPasswordHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/users/:id/lock",
				Handler: LockAccountHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/users/:id/unlock",
				Handler: UnlockAccountHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/security/login-logs",
				Handler: GetLoginLogsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/posts",
				Handler: GetPostListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/posts",
				Handler: CreatePostHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/posts/:id",
				Handler: GetPostDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/posts/:id",
				Handler: UpdatePostHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/posts/:id",
				Handler: DeletePostHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/posts/:id/publish",
				Handler: PublishPostHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/posts/:id/unpublish",
				Handler: UnpublishPostHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/pages",
				Handler: GetPageListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/pages",
				Handler: CreatePageHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/pages/:id",
				Handler: GetPageDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/pages/:id",
				Handler: UpdatePageHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/pages/:id",
				Handler: DeletePageHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/pages/:id/publish",
				Handler: PublishPageHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/pages/:id/unpublish",
				Handler: UnpublishPageHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tags",
				Handler: GetTagListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/tags",
				Handler: CreateTagHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tags/:id",
				Handler: GetTagDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/tags/:id",
				Handler: UpdateTagHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/tags/:id",
				Handler: DeleteTagHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/comments",
				Handler: GetCommentListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/comments/:id",
				Handler: GetCommentDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/comments/:id",
				Handler: UpdateCommentHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/comments/:id/approve",
				Handler: ApproveCommentHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/comments/:id/reject",
				Handler: RejectCommentHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/comments/:id/spam",
				Handler: SpamCommentHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/comments/:id",
				Handler: DeleteCommentHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/comments/batch",
				Handler: BatchCommentHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/admin"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/test/:name",
				Handler: AdminHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/admin"),
	)
}
