// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package handler

import (
	"net/http"

	"github.com/heimdall-api/admin-api/admin/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	// 登录接口 (不需要JWT验证)
	server.AddRoutes(
		[]rest.Route{
			{
				// 用户登录
				Method:  http.MethodPost,
				Path:    "/auth/login",
				Handler: LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/admin"),
	)

	// 构建需要JWT验证的中间件链，但去掉WithMiddlewares调用
	// go-zero 1.8.4 可能不支持这种中间件语法，我们需要在main.go或其他地方处理
	
	// 需要JWT验证的接口
	server.AddRoutes(
		[]rest.Route{
			{
				// 修改密码
				Method:  http.MethodPost,
				Path:    "/auth/change-password",
				Handler: ChangePasswordHandler(serverCtx),
			},
			{
				// 用户登出
				Method:  http.MethodPost,
				Path:    "/auth/logout",
				Handler: LogoutHandler(serverCtx),
			},
			{
				// 获取当前用户信息
				Method:  http.MethodGet,
				Path:    "/auth/profile",
				Handler: ProfileHandler(serverCtx),
			},
			{
				// 刷新Token
				Method:  http.MethodPost,
				Path:    "/auth/refresh",
				Handler: RefreshTokenHandler(serverCtx),
			},
			{
				// 获取页面列表
				Method:  http.MethodGet,
				Path:    "/pages",
				Handler: GetPageListHandler(serverCtx),
			},
			{
				// 创建页面
				Method:  http.MethodPost,
				Path:    "/pages",
				Handler: CreatePageHandler(serverCtx),
			},
			{
				// 获取页面详情
				Method:  http.MethodGet,
				Path:    "/pages/:id",
				Handler: GetPageDetailHandler(serverCtx),
			},
			{
				// 更新页面
				Method:  http.MethodPut,
				Path:    "/pages/:id",
				Handler: UpdatePageHandler(serverCtx),
			},
			{
				// 删除页面
				Method:  http.MethodDelete,
				Path:    "/pages/:id",
				Handler: DeletePageHandler(serverCtx),
			},
			{
				// 发布页面
				Method:  http.MethodPost,
				Path:    "/pages/:id/publish",
				Handler: PublishPageHandler(serverCtx),
			},
			{
				// 取消发布页面
				Method:  http.MethodPost,
				Path:    "/pages/:id/unpublish",
				Handler: UnpublishPageHandler(serverCtx),
			},
			{
				// 获取文章列表
				Method:  http.MethodGet,
				Path:    "/posts",
				Handler: GetPostListHandler(serverCtx),
			},
			{
				// 创建文章
				Method:  http.MethodPost,
				Path:    "/posts",
				Handler: CreatePostHandler(serverCtx),
			},
			{
				// 获取文章详情
				Method:  http.MethodGet,
				Path:    "/posts/:id",
				Handler: GetPostDetailHandler(serverCtx),
			},
			{
				// 更新文章
				Method:  http.MethodPut,
				Path:    "/posts/:id",
				Handler: UpdatePostHandler(serverCtx),
			},
			{
				// 删除文章
				Method:  http.MethodDelete,
				Path:    "/posts/:id",
				Handler: DeletePostHandler(serverCtx),
			},
			{
				// 发布文章
				Method:  http.MethodPost,
				Path:    "/posts/:id/publish",
				Handler: PublishPostHandler(serverCtx),
			},
			{
				// 取消发布文章
				Method:  http.MethodPost,
				Path:    "/posts/:id/unpublish",
				Handler: UnpublishPostHandler(serverCtx),
			},
			{
				// 获取登录日志列表
				Method:  http.MethodGet,
				Path:    "/security/login-logs",
				Handler: GetLoginLogsHandler(serverCtx),
			},
			{
				// 获取用户列表
				Method:  http.MethodGet,
				Path:    "/users",
				Handler: GetUserListHandler(serverCtx),
			},
			{
				// 创建用户
				Method:  http.MethodPost,
				Path:    "/users",
				Handler: CreateUserHandler(serverCtx),
			},
			{
				// 获取用户详情
				Method:  http.MethodGet,
				Path:    "/users/:id",
				Handler: GetUserDetailHandler(serverCtx),
			},
			{
				// 更新用户信息
				Method:  http.MethodPut,
				Path:    "/users/:id",
				Handler: UpdateUserHandler(serverCtx),
			},
			{
				// 删除用户
				Method:  http.MethodDelete,
				Path:    "/users/:id",
				Handler: DeleteUserHandler(serverCtx),
			},
			{
				// 锁定用户账户
				Method:  http.MethodPost,
				Path:    "/users/:id/lock",
				Handler: LockAccountHandler(serverCtx),
			},
			{
				// 重置用户密码
				Method:  http.MethodPost,
				Path:    "/users/:id/reset-password",
				Handler: ResetUserPasswordHandler(serverCtx),
			},
			{
				// 修改用户角色
				Method:  http.MethodPut,
				Path:    "/users/:id/role",
				Handler: UpdateUserRoleHandler(serverCtx),
			},
			{
				// 修改用户状态
				Method:  http.MethodPut,
				Path:    "/users/:id/status",
				Handler: UpdateUserStatusHandler(serverCtx),
			},
			{
				// 解锁用户账户
				Method:  http.MethodPost,
				Path:    "/users/:id/unlock",
				Handler: UnlockAccountHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/admin"),
	)

	// 测试接口
	server.AddRoutes(
		[]rest.Route{
			{
				// 测试接口
				Method:  http.MethodGet,
				Path:    "/test/:name",
				Handler: AdminHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/admin"),
	)
}
